name: Build signed APK and AAB

on:
  push:
    branches: [ "main" ]

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

jobs:
  build_apk:
    name: Build release
    runs-on: ubuntu-20.04
    steps:
    
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: app/keystore

      - name: Run tests and build release artifacts
        run: |
          ./gradlew test
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease

      - name: Upload signed APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/release/app-release.apk

      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: app/release/app-release.aab
